version: '3'
services:
  final_report_client:
    image: your_image_name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment: 
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
